FROM node:22.5.1-alpine3.20 AS build
WORKDIR /app/

COPY package-lock.json ./
COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine3.19 AS production

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]