services:
  database:
    image: mongo:8.0.0-rc15-jammy
    container_name : mongo-db-container
    command: mongod --auth
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  backend:
    container_name: todo-backend-container
    restart: always
    build: 
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - BACKENDPORT=${BACKEND_PORT}
      - MONGO_DB_HOST=mongo-db-container
    depends_on:
      - database
    networks:
      - backend
      - frontend
  
  frontend:
    container_name: todo-frontend-container
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    networks:
      - frontend

volumes:
  mongo-data:

networks:
  backend:
  frontend: